name: Deploy MEAN App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend Image
      - name: Build Backend Image
        run: docker build -t babludevops701/mean-backend:latest ./backend

      - name: Push Backend Image
        run: docker push babludevops701/mean-backend:latest

      # Build Frontend Image (no-cache)
      - name: Build Frontend Image
        run: docker build --no-cache -t babludevops701/mean-frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push babludevops701/mean-frontend:latest

      # SSH To EC2 and Deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu

            # If folder doesn't exist â†’ clone it
            if [ ! -d "DISCOVER-DOLLAR-ASSIGNMENT" ]; then
              git clone https://github.com/Bablu7011/DISCOVER-DOLLAR-ASSIGNMENT.git
            fi
            
            # Move inside project folder
            cd DISCOVER-DOLLAR-ASSIGNMENT

            # Pull latest code
            git pull origin main

            # Pull new docker images
            sudo docker pull babludevops701/mean-backend:latest
            sudo docker pull babludevops701/mean-frontend:latest

            # Restart services
            sudo docker-compose down
            sudo docker-compose up -d
