name: Deploy MEAN App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend Image
      - name: Build Backend Image
        run: docker build -t babludevops701/mean-backend:latest ./backend

      - name: Push Backend Image
        run: docker push babludevops701/mean-backend:latest

      # Build Frontend Image (force new build)
      - name: Build Frontend Image
        run: docker build --no-cache -t babludevops701/mean-frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push babludevops701/mean-frontend:latest

      # SSH To EC2 and Deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu

            # Clone project if not exists
            if [ ! -d "DISCOVER-DOLLAR-ASSIGNMENT" ]; then
              git clone https://github.com/Bablu7011/DISCOVER-DOLLAR-ASSIGNMENT.git
            fi

            cd DISCOVER-DOLLAR-ASSIGNMENT

            # Pull updated code
            git pull origin main

            echo "Removing old nginx orphan containers..."
            sudo docker ps -aq --filter "name=nginx" | xargs -r sudo docker rm -f

            echo "Pulling latest Docker images..."
            sudo docker pull babludevops701/mean-backend:latest
            sudo docker pull babludevops701/mean-frontend:latest

            echo "Stopping old containers..."
            sudo docker-compose down --remove-orphans

            echo "Starting new containers..."
            sudo docker-compose up -d

            echo "Deployment Done!"
